### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by gre** [AlexGalays/immupdate#4]
I have a tree of object with 6 nodes in total in my tree, and immupdate is extremely slow.

<img width="787" alt="screen shot 2015-10-07 at 23 28 46" src="https://cloud.githubusercontent.com/assets/211411/10351677/31eff4ea-6d4b-11e5-8032-89da8da191ac.png">

(661ms of "Self" on update function)

**Comment by gre** [comment]
(and i'm just doing stuff like this:

``` js
immupdate(dataNode, {
  children: { [i]: node }
})
```

)

**Comment by AlexGalays** [comment]
That's crazy slow... Can you paste your Graph object somewhere so I can test in the same conditions ?

**Comment by gre** [comment]
I can send you an email with it? what's your email? :)

**Comment by gre** [comment]
(found it in our github. just sent you an email)

**Comment by gre** [comment]
I was misunderstanding what my code was doing,
here is what I really wanted to do:

```
immupdate(dataNode, {
  children: { [i]: () => node }
})
```

Thanks Alex
