### ISSUE TITLE
npmignore build files

### ISSUE THREAD

**Issue by zaach** [AlexGalays/immupdate#7]
I want to use this in a React Native project but its packager tries to compile everything in node_modules, which snags on the .babelrc in this package directory because the project doesn't have the same babel presets installed. Ignoring .babelrc (and the other build files for good measure) and pushing a new version should fix it.

**Comment by AlexGalays** [comment]
Just released immupdate 0.2.1 which should fix your issue.

**Comment by zaach** [comment]
Perhaps the publish didn't go through correctly, but the lib directory is missing in 0.2.1!

**Comment by AlexGalays** [comment]
Weird... Switched to just listing all files explicitly in package.json. Please test 0.2.2

**Comment by zaach** [comment]
Works great! Thanks.
