### ISSUE TITLE
Breaking change: functions to replace values

### ISSUE THREAD

**Issue by couzic** [AlexGalays/immupdate#9]
I just found out that the latest versions of immupdate don't allow what I call "updater functions" to be passed in the spec object. I find this most regrettable, as I had come to depend on this feature, doing things like:

`import {add} from 'ramda'`

`update(state, {
  counter: add(1)
})`

It gave me a super clean and expressive API and I'm absolutely not willing to let go of this style. I understand that you must have your own reasons for this design decision, but I wanted to give you sincere feedback, and for me this change is a deal breaker.

Anyway, I'd be happy to discuss it further if you wish to.

**Comment by AlexGalays** [comment]
Thanks for the feedback, this is indeed an elegant use of that now deleted api.

Perhaps it was deleted a bit too quickly; I'm not against adding it back in.

Here's why I removed it:
- Some immupdate users update full OO objects, complete with functions. It was not the primary use case I had in mind but it can be convenient sometimes. (ex: a Filter object that has a name and a filter function)
  These functions should be left untouched; instead immupdate invoked them to get a new value. However, there is a workaround: `replace(objectWithFunctionsInside)`
- We now use typescript exclusively and, in the near future it will be possible to 100% type immupdate updates (with the `Optional` operator)
  Though it wouldn't work with update functions. I anticipated that and thus decided to no longer support these. But I believe now the best would be to keep this more dynamic api for javascript users (or typescript users who prefer to trade typesafety for convenience) and when the time comes create another branch/project for the typescript version.

All that to say, I will re-add it ;-)

**Comment by AlexGalays** [comment]
They're back in 0.4.0 ;-)

**Comment by couzic** [comment]
Thanks Alex, you made my day !

I have also switched completely to TypeScript, and many times I wish I had type-safe updates. I saw the new operator, but I'm not sure how you'd use it to achieve that goal.

Coolest thing on earth would be for immupdate to type the spec object by accepting for each field either an optional value T, or an optional Updater<T>:

`interface Updater<T> {`
   `(previousValue: T): T`
`}`

Sounds like a sweet dream, I know :)

**Comment by AlexGalays** [comment]
yeah that would be great but while I like typescript a lot, I don't think they want it to be that advanced, or at least it will take some time to get there.

**Comment by couzic** [comment]
Almost did it !

```ts
interface ValueUpdater<V> {
  (val: V): V
}

type Spec<T> = {
  [P in keyof T]?: T[P] | ValueUpdater<T[P]> | Spec<T[P]>;
  }

interface Person {
  name: string,
  lastName: string,
  age: number,
  address: {
    street: string,
    city: string
  }
}

const bob: Person = {
  name: 'Bob',
  lastName: 'Sponge',
  age: 13,
  address: {
    street: 'Sun Beach',
    city: 'Diamond Sea'
  }
};

function update<T>(host: T, spec: Spec<T>) {
}

const increment = (i: number) => i + 1;

update(bob, {
  name: 'Steve',
  lastName: () => 'Rogers',
  age: increment,
  address: {
    city: 'New York'
  }
});
```

Only problem I still can't solve is that when the updated property type is an object, in the spec any function will be considered by the compiler as a Spec, for example this will compile:
```ts
update(bob, {
  address: () => ({unknownProp: 'whatever'}) // address is an object and any function is a Spec<{}>, so it compiles
});
```

I'm suprised I could get this far (TypeScript is AWESOME) but it's frustrating to be stopped this close from the target ! Maybe I'll try again tomorrow...
